# Generated by Django 2.2.4 on 2020-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_auto_20200302_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecommand',
            name='output',
            field=models.CharField(default='True', max_length=2048),
        ),
    ]
