# Generated by Django 2.2.4 on 2020-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_auto_20200302_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecommand',
            name='output',
            field=models.CharField(default='True', max_length=255),
        ),
    ]
