# Generated by Django 2.2.4 on 2020-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_auto_20200309_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='filesystemdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesystem', models.CharField(default='True', max_length=255)),
                ('size', models.CharField(default='True', max_length=255)),
                ('used', models.CharField(default='True', max_length=255)),
                ('avail', models.CharField(default='True', max_length=255)),
                ('use', models.CharField(default='True', max_length=255)),
                ('mountpoint', models.CharField(default='True', max_length=255)),
            ],
        ),
    ]
