# Generated by Django 2.2.4 on 2020-05-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0005_filesystemdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executecommand',
            name='command',
        ),
    ]
