# Generated by Django 2.2.4 on 2020-05-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0007_onboardserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='storedata',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('project', models.CharField(default='True', max_length=15)),
                ('env', models.CharField(default='True', max_length=7)),
                ('usedspace', models.CharField(default='True', max_length=3)),
                ('ram', models.CharField(default='True', max_length=5)),
                ('swap', models.CharField(default='True', max_length=5)),
                ('os', models.CharField(default='True', max_length=10)),
                ('osversion', models.CharField(default='True', max_length=10)),
            ],
        ),
    ]
