# Generated by Django 2.2.4 on 2020-05-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0008_storedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='usedspace',
            field=models.CharField(default='True', max_length=4),
        ),
    ]
