# Generated by Django 2.2.4 on 2020-05-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0010_auto_20200520_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='swap',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
