# Generated by Django 2.2.4 on 2020-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0012_auto_20200526_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='hostname',
            field=models.CharField(default='True', max_length=32),
        ),
    ]
