# Generated by Django 2.2.4 on 2020-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0013_storedata_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='passwdauth',
            field=models.CharField(default='True', max_length=5),
        ),
    ]
