# Generated by Django 2.2.4 on 2020-06-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0014_storedata_passwdauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='portmonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('pid', models.CharField(max_length=8)),
                ('status', models.CharField(default='DOWN', max_length=5)),
            ],
        ),
    ]
