# Generated by Django 2.2.4 on 2020-07-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0015_portmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='mountpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesystem', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=6)),
                ('used', models.CharField(max_length=5)),
                ('avail', models.CharField(max_length=6)),
                ('use', models.CharField(max_length=5)),
                ('mount', models.CharField(max_length=255)),
            ],
        ),
    ]
