# Generated by Django 2.2.4 on 2020-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0019_auto_20200716_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='applogfilesize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesize', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='portinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto', models.CharField(max_length=255)),
                ('recv', models.CharField(max_length=2)),
                ('send', models.CharField(max_length=2)),
                ('laddress', models.CharField(max_length=32)),
                ('faddress', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=8)),
                ('pid', models.CharField(max_length=50)),
            ],
        ),
    ]
