# Generated by Django 2.2.4 on 2020-08-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0023_auto_20200819_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='portdetails',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=5)),
            ],
        ),
    ]
