# Generated by Django 2.2.4 on 2020-06-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmonitoring',
            name='ownerphno',
        ),
    ]
