# Generated by Django 2.2.4 on 2020-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0002_remove_urlmonitoring_ownerphno'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmonitoring',
            name='ownerphno',
            field=models.IntegerField(default=7483036389, max_length=10),
        ),
    ]
