# Generated by Django 2.2.4 on 2020-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0003_urlmonitoring_ownerphno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmonitoring',
            name='ownerphno',
            field=models.CharField(default=7483036389, max_length=10),
        ),
    ]
