# Generated by Django 2.2.4 on 2020-06-11 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0004_auto_20200611_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmonitoring',
            name='ownerphno',
            field=models.CharField(default=7483036389, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
