# Generated by Django 2.2.4 on 2020-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0005_auto_20200611_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmonitoring',
            name='ownerphno',
        ),
        migrations.AddField(
            model_name='urlmonitoring',
            name='ownerphnofirst',
            field=models.CharField(default=74830, max_length=5),
        ),
        migrations.AddField(
            model_name='urlmonitoring',
            name='ownerphnosecond',
            field=models.CharField(default=36389, max_length=5),
        ),
    ]
