# Generated by Django 2.2.4 on 2020-06-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0008_auto_20200611_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmonitoring',
            name='ownerphnofirst',
            field=models.TextField(default=0, max_length=10),
        ),
    ]
