# Generated by Django 2.2.4 on 2020-06-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0011_auto_20200611_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmonitoring',
            name='id',
            field=models.IntegerField(editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
