# Generated by Django 2.2.4 on 2020-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0012_auto_20200611_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmonitoring',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlmonitoring',
            name='ip',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
