# Generated by Django 2.2.4 on 2020-06-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlmonitoring', '0014_auto_20200611_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='urlmonitoring',
        ),
    ]
