# Generated by Django 2.2.4 on 2019-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='errinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='serverinfo',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=15)),
                ('os', models.CharField(max_length=15)),
                ('osversion', models.CharField(max_length=10)),
                ('xroadcomponent', models.CharField(max_length=10)),
                ('xroadcomponentversion', models.CharField(max_length=10)),
                ('statuscode', models.IntegerField()),
                ('message', models.CharField(default='True', max_length=255)),
            ],
        ),
    ]
