# Generated by Django 2.2.4 on 2019-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20191120_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='statuscode',
            field=models.CharField(max_length=3),
        ),
    ]
