# Generated by Django 2.2.4 on 2019-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20191120_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='errinfo',
        ),
    ]
