# Generated by Django 2.2.4 on 2019-12-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0006_auto_20191213_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='statuscode',
            field=models.CharField(default='True', max_length=8),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='url',
            field=models.CharField(default='True', max_length=255),
        ),
    ]
