# Generated by Django 2.2.4 on 2019-12-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_auto_20191231_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicinfo',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
